---
- name: Add PHP repository
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: Install packages
  ansible.builtin.apt:
    name:
      - php8.2-mysql
      - php8.2-fpm
      - php8.2-mbstring
      - php8.2-xml
      - php8.2-bcmath
      - php8.2-curl
      - php8.2-cli
      - php8.2-common
      - php8.2-zip
      - php8.2-gd
      - php8.2-swoole
      - php8.2-soap
      - nginx
      - supervisor
      - net-tools
    state: present
    update_cache: true

- name: Add sail config
  ansible.builtin.template:
    src: sail.j2
    dest: /etc/php/8.2/cli/conf.d/99-sail.ini
    mode: preserve

- name: Add supervisor config
  ansible.builtin.template:
    src: supervisor.j2
    dest: /etc/supervisor/conf.d/laravel_worker.conf
    mode: preserve
  notify:
    - Restart supervisor
    - Supervisor restart

- name: Add nginx config
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/laravel
    mode: preserve

- name: Create nginx symlink
  ansible.builtin.command:
    cmd: ln -s /etc/nginx/sites-available/laravel /etc/nginx/sites-enabled
    creates: /etc/nginx/sites-enabled/laravel
  notify:
    - Restart nginx
