---

- name: Add Certbot repository
  ansible.builtin.apt_repository:
    repo: "ppa:certbot/certbot"
    state: present

- name: Install Nginx & Cerbot
  ansible.builtin.apt:
    name: " {{ item }} "
    update_cache: true
    with_items:
      - nginx
      - python3-certbot-nginx
    state: present

- name: Add server block
  ansible.builtin.template:
    src: example.j2
    dest: /etc/nginx/sites
    mode: preserve


