---
- name: Add PHP repository
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: Install PHP & dependencies
  ansible.builtin.apt:
    name:
      - php8.2-mysql
      - php8.2-fpm
      - php8.2-mbstring
      - php8.2-xml
      - php8.2-bcmath
      - php8.2-curl
      - php8.2-cli
      - php8.2-common
      - php8.2-zip
      - php8.2-gd
      - pdo pdo_mysql
    state: present
    update_cache: true