---
- name: Install Nginx
  ansible.builtin.apt:
    name:
      - nginx
    state: present

- name: Add server block
  ansible.builtin.template:
    src: example.j2
    dest: /etc/nginx/sites
    mode: preserve
