---
- name: Add PHP repository
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: Install PHP 8.2 & dependencies
  ansible.builtin.apt:
    name:
      - php8.2-mysql
      - php8.2-fpm
      - php8.2-mbstring
      - php8.2-xml
      - php8.2-bcmath
      - php8.2-curl
      - php8.2-cli
      - php8.2-common
      - php8.2-zip
      - php8.2-gd
      - pdo pdo_mysql
    state: present
    update_cache: true

- name: Add config.ini
  ansible.builtin.template:
    src: config.js
    dest: /etc/php/8.2/fpm.ini
    mode: preserve

- name: Restart FPM
  ansible.builtin.service:
    name: php8.2-fpm
    state: restarted
    enabled: true

- name: Download specific Moodle version
  ansible.builtin.git:
    repo: "{{ moodle_git_repository }}"
    dest: "{{ moodle_root_path }}"
    version: "MOODLE_{{ moodle_version.split('.')[0] }}{{ moodle_version.split('.')[1] }}_STABLE"
