---
- name: Add PHP repository
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: Install PHP 8.2 & dependencies
  ansible.builtin.apt:
    name:
      - php8.2-mysql
      - php8.2-fpm
      - php8.2-mbstring
      - php8.2-xml
      - php8.2-bcmath
      - php8.2-curl
      - php8.2-cli
      - php8.2-common
      - php8.2-zip
      - php8.2-gd
      - php8.2-swoole
      - php8.2-soap
    state: present
    update_cache: true

- name: Add sail config
  ansible.builtin.template:
    src: sail.j2
    dest: /etc/php/8.2/cli/conf.d/99-sail.ini
    mode: preserve

- name: Add supervisor config
  ansible.builtin.template:
    src: supervisor.j2
    dest: /etc/supervisor/conf.d/laravel.conf
    mode: preserve


