- name: Deploys VM based on cloud image
  hosts: localhost
  gather_facts: true
  become: yes
  vars:
    pool_dir: "/var/lib/libvirt/images"
    vm: ubuntu
    vcpus: 1
    ram_mb: 1024
    cleanup: no
    net: default
    ssh_pub_key: "/home/danielpepuho/.ssh/id_rsa.pub"
    interface_name: "enp1s0"

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
      vars:
        libvirt_pool_dir: "{{ pool_dir }}"
        vm_name: "{{ vm }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_net: "{{ net }}"
        cleanup_tmp: "{{ cleanup }}"
        ssh_key: "{{ ssh_pub_key }}"