name: ansible-lint
on:
  pull_request:

jobs:
  build:
    name: Check the .yml using ansible lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible Galaxy dependencies
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy collection install community.mysql
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main